### ISSUE TITLE
occupied  spot

### ISSUE THREAD

**Issue by evanillaa** [JericoFX/qb-garages#1]
When a vehicle is ejected and the place is reserved, an error message does not appear
The place is occupied by another car
Two points must be added to the response
And check the place if it is empty. He prespons the vehicle
And if he is an occupier, a message will appear that he cannot remove the vehicle. The place is reserved

```
parkSpots = {
      vector4(269.07, -325.86, 44.31, 250.79),
        vector4(269.07, -325.86, 44.31, 250.79),
},
```

**Comment by evanillaa** [comment]
Also, is the new phone ready?

**Comment by JericoFX** [comment]
Hi, there isnt "spots" for the car, the script will check if there is space to spawn the next vehicle, can you provide images?
