### ISSUE TITLE
[BUG] Phone broken and garages not storing cars when pressing E

### ISSUE THREAD

**Issue by MrMCore** [JericoFX/qb-garages#6]
Pressing E nothing happens Leaves my phone broken

Go to any garage and press E wont store my car and leaves phone script broken

Latest Version of QBCore

**Comment by JericoFX** [comment]
Need to check the phone, mine broken too, need to check if is the way that the phone grabs the car from db

**Comment by MrMCore** [comment]
Nice :) cant wait to see it working really nice work with the UI and other stuff 😄

**Comment by JericoFX** [comment]
i have to turn back on using polyzones because if you edit the config.lua the phone breaks, so i create another config specific to this resource
