### ISSUE TITLE
[BUG] Unable to save vehicle fuel and other error

### ISSUE THREAD

**Issue by MercedessBenz** [JericoFX/qb-garages#7]
**vehicle has 50% fuel left, park the vehicle and take out of the garage the fuel is back to 100%**

**Comment by MercedessBenz** [comment]
**When the server restarts, I go to the garage impound press E, the screen is frozen, only the mouse pointer is displayed, and in F8 this error is displayed**

![image](https://user-images.githubusercontent.com/25920716/141771586-9d1653c7-596c-4c75-bab2-86bebd5f77b8.png)
**Line code**
![image](https://user-images.githubusercontent.com/25920716/141771699-f9e6cabb-7989-4fd8-9ff3-9269546b6475.png)

**Comment by MercedessBenz** [comment]
**Database related errors appear in the console when the server is restarted**

![image](https://user-images.githubusercontent.com/25920716/141777432-493a3056-dce1-4cfe-872b-e0cbd6744f95.png)

**Comment by MercedessBenz** [comment]
**I bought a motorbike and put it in the garage, I get this error (The screen shows the mouse pointer and freezes)**

![image](https://user-images.githubusercontent.com/25920716/142032670-7fd57f59-85ed-404e-a2f9-edf8be0e5b49.png)
**line code**
![image](https://user-images.githubusercontent.com/25920716/142032996-57113102-e069-4eb9-8ba6-6714a88c1ca3.png)

**Comment by JericoFX** [comment]
> 
> 
> **When the server restarts, I go to the garage impound press E, the screen is frozen, only the mouse pointer is displayed, and in F8 this error is displayed**
> 
> ![image](https://user-images.githubusercontent.com/25920716/141771586-9d1653c7-596c-4c75-bab2-86bebd5f77b8.png) **Line code** ![image](https://user-images.githubusercontent.com/25920716/141771699-f9e6cabb-7989-4fd8-9ff3-9269546b6475.png)

Try to put False in there, just false

**Comment by JericoFX** [comment]
> 
> 
> **I bought a motorbike and put it in the garage, I get this error (The screen shows the mouse pointer and freezes)**
> 
> ![image](https://user-images.githubusercontent.com/25920716/142032670-7fd57f59-85ed-404e-a2f9-edf8be0e5b49.png) **line code** ![image](https://user-images.githubusercontent.com/25920716/142032996-57113102-e069-4eb9-8ba6-6714a88c1ca3.png)

Did you teleport?, because this error happend when you teleport to the garage.

**Comment by MercedessBenz** [comment]
**Yes, I /tpm go to the garage**

**Comment by MercedessBenz** [comment]
> > **I bought a motorbike and put it in the garage, I get this error (The screen shows the mouse pointer and freezes)**
> > ![image](https://user-images.githubusercontent.com/25920716/142032670-7fd57f59-85ed-404e-a2f9-edf8be0e5b49.png) **line code** ![image](https://user-images.githubusercontent.com/25920716/142032996-57113102-e069-4eb9-8ba6-6714a88c1ca3.png)
> 
> Did you teleport?, because this error happend when you teleport to the garage.

**I bought a car and ran to the garage to put it in and it was faulty**

**Comment by JericoFX** [comment]
i will check today

**Comment by JericoFX** [comment]
so i download again this repo and travel to all the garages and no error

**Comment by MercedessBenz** [comment]
> **Database related errors appear in the console when the server is restarted**
> 
> ![image](https://user-images.githubusercontent.com/25920716/141777432-493a3056-dce1-4cfe-872b-e0cbd6744f95.png)

**What about the database error that appears on the console when opening the server?**

**Comment by JericoFX** [comment]
did you update the sql?

**Comment by MercedessBenz** [comment]
> 

**That's right, I updated to the latest version**

**Comment by MercedessBenz** [comment]
**I wonder, if the player leaves his vehicle somewhere and it is deleted by the fiveM system because the area is not visited by players, how will the player get the car back?

Only wait until the server restarts, then the car will return to the garage???**

**There should be a solution to recover the car to the garage with a certain fee**

**Comment by MercedessBenz** [comment]
**I wonder, if the player leaves his vehicle somewhere and it is deleted by the fiveM system because the area is not visited by players, how will the player get the car back?**

**Only wait until the server restarts, then the car will return to the garage???**

**There should be a solution to recover the car to the garage with a certain fee**

**Comment by JericoFX** [comment]
no, because thats a Onesync stuff, check the documentation about Onesync and you will underestand better, and thje fee is hard to say, when the resource start it will check if there is any car out will put the car in the default depot, you need to check if the player is online and the car is not used, and is hard to do that because maybe the player just run out of the scope and when he try to come back the car isnt there just because the script delete it.

**Comment by MercedessBenz** [comment]
@JericoFX 

I do not understand why

I got a rather confusing error, I deleted all the data in player_vehicles and I bought a car, put it in the garage with the engine damaged, after taking the car out the engine returned to 100%

But if I buy the next car, the 2nd car doesn't have the same problem, only the first car

I tested on localhost, I don't know if other players have the same problem

Do you know what this error is?

**Comment by MercedessBenz** [comment]
Why when the car is taken out from your garage script are all 100% engine

QBCore's original script is not like that

https://streamable.com/rv8lth

**Comment by RadhwaneDZ** [comment]
this is not related to qb-garages but its related to qb-pmi 
im using the latest qbcore release and i already added functions to other resources everything work fine except when you click on loop icon  getting this error 

`TypeError: t.getPersonRecords is not a function (@qb-pmi/client/html/js/chunk-vendors.js:7)`
also if you do a search by name or fingerprint or ID nothing work 
sorry about posting this here again

**Comment by JericoFX** [comment]
> 

did you save the car with the qb garages and not with my garage, my garage handle the damage when you save the vehicle not when you pull out

**Comment by MercedessBenz** [comment]
@JericoFX 

https://streamable.com/antj5f

**Comment by JericoFX** [comment]
https://streamable.com/p39sqg visual damage never get save, just engine, fuel, wheels and some windows

**Comment by MercedessBenz** [comment]
> https://streamable.com/p39sqg visual damage never get save, just engine, fuel, wheels and some windows

But in the video I sent, I put the car in the garage with the engine damaged, but after I took the car out the engine went to 100%.

**Comment by JericoFX** [comment]
thanks for reporting, can you try now with the lastest commit?

**Comment by MercedessBenz** [comment]
I just retested

Everything seems to work fine, but where will the media's data be saved?

Can you make 1 language separate script so people can easily translate into their language?

**Comment by MercedessBenz** [comment]
I just checked again

Everything seems to be working fine for the garage, but where will the vehicle data be saved?

For hayesdepot garages that do not save data, the default retrieved vehicle will be 100% engine, body, and fuel.

Can you create a separate script for 1 language so that everyone can easily translate into their language?

**Comment by MercedessBenz** [comment]
I just checked again

Everything seems to be working fine for the garage, but where will the vehicle data be saved?

For hayesdepot garages that do not save data, the default retrieved vehicle will be 100% engine, body, and fuel.

Vehicle tuning does not save data

Can you create a separate script for 1 language so that everyone can easily translate into their language?

**Comment by MercedessBenz** [comment]
I just checked again

Engine, body, fuel data seems to work fine for the garage, but where will the vehicle data be saved?

For hayesdepot garages that do not save data, the default retrieved vehicle will be 100% engine, body, and fuel.

Vehicle tuning does not save data

Can you create a separate script for 1 language so that everyone can easily translate into their language?

**Comment by JericoFX** [comment]
"For hayesdepot garages that do not save data, the default retrieved vehicle will be 100% engine, body, and fuel."
Data is saved in a sql or kvp you decide.

"Vehicle tuning does not save data"
This is handle by the qb natives.

"Can you create a separate script for 1 language so that everyone can easily translate into their language?"
i left the source code for that reason, is easy to add a languaje.
