### ISSUE TITLE
[BUG] No Keys

### ISSUE THREAD

**Issue by ItssJxstnDe** [JericoFX/qb-garages#8]
If Park Vehicle Out i get no keys!

**Comment by ItssJxstnDe** [comment]
i tried but did not work

**Comment by ItssJxstnDe** [comment]
and btw is there an updated version of this?
because i like this garage

**Comment by JericoFX** [comment]
i actually never finished the other version.

**Comment by ItssJxstnDe** [comment]
Can you pls do IT 😭😭

**Comment by ItssJxstnDe** [comment]
ill try tommow will give feedback here!

**Comment by JericoFX** [comment]
awesome, but remember, i cant support an 2 years old code, this need to be rewrite

**Comment by ItssJxstnDe** [comment]
Can you do a rewrite? Pls?

**Comment by JericoFX** [comment]
imposible, take much time i have another projects
